language: ruby
cache: bundler
sudo: false

rvm:
  - 2.6.6
env:
  global:
    - RAILS_ENV=test
    - DB=sqlite
before_install:
    - gem update --system
    - gem install bundler
script:
  - bundle exec rake db:setup spec
