name: Deploy to Heroku

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: ${{ secrets.HEROKU_APP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # 0 indicates fetching history for all branches and tags. This is required to push to Heroku.
          fetch-depth: 0

      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/chore/deploy-onesiam'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
          git push -f production origin/chore/deploy-onesiam:refs/heads/master
